config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :social_media_accounts
    resources :social_media_marketing_events
    resources :facebook_pages, only: [:create, :destroy, :show]
    resources :social_media_posts, only: [:create, :destroy] do
      member do
        put :repost
      end
    end
  end

  get 'auth/:provider/callback', to: 'admin/social_media_accounts#create', as: :oauth_redirect
  get 'auth/facebook', to: 'auth#facebook'
  get 'auth/twitter', to: 'auth#twitter'
  match 'auth/failure', to: redirect('/admin/social_media_accounts'), via: [:get, :post]

end

app/models/spree/social_media_post.rb
module Spree
  class SocialMediaPost < Spree::Base

    ## TODO: Can we rename this to social_media_publishable? postable is no word.
    belongs_to :social_media_publishable, polymorphic: true
    has_many :social_media_post_images, dependent: :destroy
    has_many :images, through: :social_media_post_images

    ## TODO: Why is this limit present? Should be only for Twitter. Also, extract to a constant.(done)
    ## TODO: Add validations for presence of social_media_publishable
    validates :post_message, presence: true
    validates :post_message, length: { maximum: 140 }, if: :social_media_publishable_is_twitter_account?
    validates :social_media_publishable, presence: true
    accepts_nested_attributes_for :images

    after_create :send_post_and_assign_post_id
    after_destroy :destroy_post_on_social_media

    def send_post_and_assign_post_id
      begin
        post_id = social_media_publishable.post(post_message, images)
        self.update(post_id: post_id, error_message: nil)
      rescue StandardError => e
        self.update(error_message: e.message)
      end
    end
    
    private
      def destroy_post_on_social_media
        social_media_publishable.remove_post(post_id) if post_id?
      end

      def social_media_publishable_is_twitter_account?
        social_media_publishable.class == Spree::TwitterAccount
      end
  end
end

app/controllers/spree/admin/social_media_posts_controller.rb
module Spree
  module Admin
    class SocialMediaPostsController < Spree::Admin::ResourceController
      before_filter :fetch_post, only: [:destroy, :repost]

      def create
        @social_media_post = Spree::SocialMediaPost.new(post_params)

        ## TODO: We don't need .present(done)
        if params[:social_media_post][:image]
          @social_media_post.images.build(post_image_params)
        end

        if @social_media_post.save
          flash[:success] = 'Post Added'
        else
          flash[:error] = @social_media_post.errors.full_messages.join(', ')
        end
        redirect_to :back
      end

      def destroy
        if @post.destroy
          flash[:success] = 'Post Removed'
        else
          flash[:error] = 'Could Not Remove Post'
        end
        redirect_to :back
      end

      def repost
        @post.send_post_and_assign_post_id
        redirect_to :back
      end

      private

        def fetch_post
          unless @post = Spree::SocialMediaPost.find_by(id: params[:id])
            flash[:alert] = 'Post Does Not Exist'
            redirect_to :back
          end
        end

        def post_params
          params.require(:social_media_post).permit(:post_message, :social_media_publishable_id, :social_media_publishable_type)
        end

        def post_image_params
          params.require(:social_media_post).require(:image).permit(:attachment)
        end
    end
  end
end

app/views/spree/admin/social_media_posts/_form.html.erb
<%= post_form.hidden_field :social_media_publishable_id, value: social_media_publishable_id %>
<%= post_form.hidden_field :social_media_publishable_type, value: social_media_publishable_type %>
<div>
  <div class="row no-padding">
    <div class="col-md-12">
      <div class="col-md-4">
        <%= post_form.fields_for post_form.object.images.build do |image_form| %>
          <div data-hook="file">
            <%= image_form.label :attachment, Spree.t(:image) %>
            <%= image_form.file_field :attachment %>
          </div>
        <% end %>
      </div>
      <div class="col-md-8">
        <div data-hook="message"=>
          <%= post_form.label :post_message, 'Message' %>
          <%= post_form.text_area :post_message, class: "form-control #{ 'character-limited' if limit_message_characters }", rows: 4, data: { character_limit: 140, remove_dynamic_code: false } %>
        </div>
      </div>
    </div>
  </div>
  <div class='row'>
    <% if limit_message_characters %>
      <div class="col-md-8">
      </div>
      <div class="col-md-1 remaining_character_block">
        <span id='remaining_character_span'></span>
      </div>
      <div class="col-md-3">
      </div>
    <% end %>
  </div>
</div>
<%= button Spree.t('Submit New Post'), 'ok', 'submit', { class: 'btn-success', data: { disable_with: 'Submitting...' } } %>

app/views/spree/admin/social_media_posts/_show.html.erb
<div id="posts-list" data-hook>
  <h4>
    Recent Posts
  </h4>
  <% if posts.empty? %>
    <h5>You have no posts for this account.</h5>
  <% else %>
    <table class="table" id='listing_pages' data-hook>
      <thead>
        <tr data-hook="social_media_publishable_header">
          <th><%= Spree.t(:post) %></th>
          <th><%= Spree.t(:image) %></th>
          <th><%= Spree.t(:error) %></th>
          <th><%= Spree.t(:posted_at) %></th>
          <th class="actions">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% posts.each do |post| %>
          <tr>
            <td class='social-media-post-message-column'>
              <%= post.post_message %>
            </td>
            <td>
              <%= image_tag post.images.first.attachment.url(:mini) if post.images.exists? %>
            </td>
            <td class='social-media-post-error-message-column'>
              <%= post.error_message %>
            </td>
            <td>
              <%= post.created_at.strftime('%Y-%m-%d %I:%M %p') %>
            </td>
            <td>
              <%= link_to admin_social_media_post_path(post), method: :delete, class: 'btn btn-danger btn-sm icon-link with-tip action-delete no-text', data: { confirm: 'Are you sure you want to remove this post?', remote: false } do %>
                <span class='icon icon-delete'></span>
              <% end %>
              <% unless post.post_id %>
                <%= link_to repost_admin_social_media_post_path(post), method: :put, class: 'btn btn-primary btn-sm icon-link with-tip no-text', data: { remote: false } do %>
                  <span class='icon glyphicon-retweet'></span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: posts } %>
  <% end %>
</div>